### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: 'black'

### ISSUE THREAD

**Issue by HongLouyemeng** [habanero-lab/APPy#1]
Hi,Thank you for your work, in the process of using it I acquired an error
```python
import torch
import appy
a = torch.tensor([1,2,3,4,5],device='cuda:0')
b = torch.tensor([1,2,3,4,5],device='cuda:0')
@appy.jit
def add(a,b):
    #pragma parallel for
    for i in range(len(a)):
        a[i]+=b
add(a, b)
```
![image](https://github.com/habanero-lab/APPy/assets/48181529/c68ea912-8e99-407c-b145-a1cd4133ed29)
![image](https://github.com/habanero-lab/APPy/assets/48181529/69ac2571-5f18-4f7f-9536-d56494069c19)

**Comment by vesuppi** [comment]
Hi, 

Thank you for reporting that! `black` is a package that APPy uses to format generated files, you should be able to fix the problem by running `pip install black`. Alternatively I've also just updated the setup.py to add `black` as a required package. So if you do `git pull` and `pip install -e .` again, it should automatically install black as well. 

Plus, I've also just ran your test code on my machine and it ran without a problem. But one minor thing is that I believe `a[i]+=b` should be `a[i]+=b[i]`?

**Comment by HongLouyemeng** [comment]
Thanks for your reply.
